#!/usr/bin/env bash
#SBATCH -J 005_annotate_cells.R
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=JohnDoe@mail.com
#SBATCH --partition=himem
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=40G
#SBATCH --time=00:15:00
#SBATCH --output=slurm_out/%x_%A.out
#SBATCH --error=slurm_out/%x_%A.out

sample_id="6509_A"
meta="${PWD}/data/Xenium/processed/6509_A__BANKSY_metadata.rds"
# Pleae note that exp_counts is generated by UTILS-save_expression.sh and is the ROI
exp_counts="${PWD}/data/Xenium/processed/6509_A__RNA_counts.rds"
annot_clusters="${PWD}/misc/manual_annot.xlsx"
output_dir="${PWD}/data/Xenium/processed"
cells_oi="${PWD}/misc/6509_A_roi_cell_ids.csv"

sheet_name="BANKSY"
cluster_varname="BANKSY_snn_res.0.5"

echo "Activating conda environment..."
source "${CONDA_PREFIX}/bin/activate" "r-4.3.3"

Rscript ${PWD}/preprocessing/Xenium/005_annotate_cells.R \
    --output_dir ${output_dir} \
    --sample_id ${sample_id} \
    --sheet_name ${sheet_name} \
    --meta ${meta} \
    --cluster_varname ${cluster_varname} \
    --exp_counts ${exp_counts} \
    --annot_clusters ${annot_clusters} \
    --cells_oi ${cells_oi}