---
title: "Notebook to reproduce Figure 2e & 2f"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
author: "Joan Kant"
params:
    output_dir: "output/VisiumHD"
    sample_id:  "Gaiti_Yiyan__6425_cortex_1_A1"
    segmentation_masks_path: "data/VisiumHD/processed/6425_cortex_1_A1__masks.json"
    seurat_obj_path: "data/VisiumHD/processed/6425_cortex_1_A1.rds"
    output_dir: "output/VisiumHD"
    k_neighbors: 30
    pseudobulk_scores_path: "data/VisiumHD/processed/10k/6425_combined_pseudobulk_scores_k30.rds"
    n_iter: 10000
    lower_limit: 0.10
    upper_limit: 0.90
    scale_factors_path: "/cluster/projects/gaitigroup/Data/GBM_VisiumHD/20240708_LH00244_0121_B22MN7GLT3_Gaiti_Yiyan_Visium/6425_cortex_1_A1/outs/binned_outputs/square_002um/spatial/scalefactors_json.json"
    seurat_obj_subset_path: "data/VisiumHD/processed/10k/6425_combined_seurat_obj_meanshortest_k30.rds"
    markers_path: "data/VisiumHD/processed/6425_cortex_1_A1_markers_by_celltype.rds"

output: html_document
---


```{r, rmarkdown-setup, include=FALSE}
knitr::opts_knit$set(
    root.dir = here::here()
)
knitr::opts_chunk$set(
    fig.align = "center", fig.width = 12, warning = FALSE
)
pacman::p_load(GaitiLabUtils, GBMutils, glue, data.table, tidyverse, stringr, sf, rjson, Seurat)
logr <- init_logging()


params <- list()
params$sample_id <- "Gaiti_Yiyan__6425_cortex_1_A1"
params$segmentation_masks_path <- glue("data/VisiumHD/processed/{params$sample_id}__masks.json")
params$seurat_obj_path <- glue("data/VisiumHD/processed/{params$sample_id}.rds")
params$output_dir <- "output/VisiumHD"
params$k_neighbors <- 30

params$pseudobulk_scores_path <- glue("data/VisiumHD/processed/10k/6425_combined_pseudobulk_scores_k{params$k_neighbors}.rds")
params$n_iter <- 10000
params$lower_limit <- 0.10
params$upper_limit <- 0.90
params$scale_factors_path <- glue("/cluster/projects/gaitigroup/Data/GBM_VisiumHD/20240708_LH00244_0121_B22MN7GLT3_Gaiti_Yiyan_Visium/{params$sample_id}/outs/binned_outputs/square_002um/spatial/scalefactors_json.json")
params$seurat_obj_subset_path <- glue("data/VisiumHD/processed/10k/6425_combined_seurat_obj_meanshortest_k{params$k_neighbors}.rds")
params$markers_path <- glue("data/VisiumHD/processed/{params$sample_id}_markers_by_celltype.rds")
```

## Spatial cell type distribution
```{r, spatial-cell-type-distribution}
# Setup color palette
log_info("Load color palette...")
palette <- GBMutils::load_color_palette("Spatial_CellClass_L1")

log_info("Load scalefactors...")
scalefactors <-
    fromJSON(file = params$scale_factors_path)

log_info("Load segmentation masks...")
gdf <- read_sf(params$segmentation_masks_path) %>% mutate(geometry_px = geometry)
# Remove coordinate systems, just want to use cartesian system
st_crs(gdf) <- NA


log_info("Load Seurat object...")
seurat_obj <- readRDS(params$seurat_obj_path)

log_info("Combine metadata and segmentation masks...")
meta_sdf <- sf::st_as_sf(
    (seurat_obj@meta.data) %>%
        left_join(gdf, by = "id")
) %>%
    # Convert to px to microns
    mutate(geometry = geometry_px * scalefactors$microns_per_pixel)

ncells_by_celltype <- meta_sdf %>%
    count(BANKSY_snn_res.2_annot) %>%
    mutate(label = paste0("No. cells=", prettyNum(n, big.mark = ",")))

# Plot by cell type
p <- ggplot(meta_sdf %>% filter(BANKSY_snn_res.2_annot %in% c("Neuron", "Malignant"))) +
    geom_sf(aes(fill = BANKSY_snn_res.2_annot), color = NA, show.legend = FALSE) +
    GBMutils::GBM_theme() +
    ggh4x::facet_wrap2(. ~ BANKSY_snn_res.2_annot, axes = "all", nrow = 1) +
    scale_fill_manual(
        values = GBMutils::load_color_palette("Spatial_CellClass_L1"),
        guide = guide_legend(override.aes = list(size = 5), title = "Cell type")
    ) +
    geom_sf_text(
        data = ncells_by_celltype %>% filter(BANKSY_snn_res.2_annot %in% c("Neuron", "Malignant")), x = -Inf, y = Inf, aes(label = label),
        hjust = -0.1, vjust = 1.2, size = 3
    ) +
    coord_sf() +
    scale_y_reverse() +
    labs(
        x = "X (µm)", y = "Y (µm)",
    ) +
    theme(aspect.ratio = 1, axis.text = element_blank(), axis.ticks = element_blank())

ggsave(plot = p, filename = glue("Fig2e-{params$sample_id}_spatial_Neuron_Malignant.pdf"), path = params$output_dir, width = 10, height = 10)
```

## Relationship proximity Malignant cells - Neurons and subtype signatures

```{r, neuron-malignant-continuous-distances}
# Define bin names
categories <- c(
    paste0("<", params$lower_limit * 100, "%"),
    "between",
    paste0(">", params$upper_limit * 100, "%")
)
color_gradient <- setNames(RColorBrewer::brewer.pal(n = 8, name = "Blues")[c(3, 5, 8)], categories)

colors <- c(palette["Neuron"], color_gradient)

log_info("Load Seurat object subset...")
seurat_obj_subset <- readRDS(params$seurat_obj_subset_path)

dist_obs_df <- seurat_obj_subset@meta.data %>%
    mutate(
        sample = case_when(
            sample == "PT1" ~ "Gaiti_Yiyan__6425_cortex_1_A1",
            sample == "PT3" ~ "Gaiti_Yiyan__6425_cortex_3_D1",
        ),
        cat_dist = ifelse(cat_dist == paste0(
            params$lower_limit * 100, "% <= mean distance <= ",
            params$upper_limit * 100, "%"
        ), "between", cat_dist),
    ) %>%
    select(sample, id, cat_dist, mean_dist, BANKSY_snn_res.2_annot)
dist_obs_df$id <- str_split(dist_obs_df$id, "_", simplify = TRUE, n = 2)[, 2]

log_info("Combine metadata and segmentation masks...")
dist_obs_sdf <- meta_sdf %>%
    filter(BANKSY_snn_res.2_annot %in% c("Neuron", "Malignant")) %>%
    select(id, geometry, BANKSY_snn_res.2_annot) %>%
    left_join(dist_obs_df %>%
        filter(sample == params$sample_id)) %>%
    # Convert to px to microns
    mutate(
        vis_label = factor(ifelse(BANKSY_snn_res.2_annot == "Neuron", "Neuron", cat_dist), levels = names(colors))
    )

myfuns_nam <- list(close = min, far = max)

list_val <- lapply(myfuns_nam, function(f) f(dist_obs_sdf %>% filter(BANKSY_snn_res.2_annot == "Malignant") %>% pull(mean_dist)))


p <- ggplot() +
    geom_sf(data = dist_obs_sdf %>% filter(BANKSY_snn_res.2_annot == "Malignant"), aes(fill = mean_dist), color = NA) +
    GBMutils::GBM_theme() +
    scale_fill_distiller(
        palette = "Blues", direction = 1,
        breaks = unlist(list_val),
        guide = guide_colorbar(
            override.aes = list(size = 5),
            title.position = "top",
            title = glue("Proximity to {params$k_neighbors} nearest Neurons (µm)"),
            barwidth = unit(8, "lines"), barheight = unit(0.8, "lines")
        )
    ) +
    ggnewscale::new_scale_fill() +
    geom_sf(
        data = dist_obs_sdf %>% filter(BANKSY_snn_res.2_annot == "Neuron"),
        fill = GBMutils::load_color_palette("Spatial_CellClass_L1")[["Neuron"]], color = NA
    ) +
    coord_sf() +
    scale_y_reverse() +
    labs(
        x = "X (µm)", y = "Y (µm)",
        subtitle = paste0("No. cells=", prettyNum(dist_obs_sdf %>% filter(BANKSY_snn_res.2_annot %in% c("Malignant", "Neuron")) %>% nrow(), big.mark = ","))
    ) +
    theme(aspect.ratio = 1, axis.text = element_blank(), axis.ticks = element_blank())

ggsave(plot = p, filename = glue("Fig2e-{params$sample_id}_dist_gradient_k{params$k_neighbors}.pdf"), path = params$output_dir)
```

```{r, vis-stat}
log_info("Load pseudobulk scores...")
pseudobulk_scores_df <- readRDS(params$pseudobulk_scores_path)
# split into observed and shuffled
obs_df <- pseudobulk_scores_df %>%
    filter(ix == "cat_dist") %>%
    mutate(AddModuleScore = as.numeric(AddModuleScore)) %>%
    rename(AddModuleScore_obs = AddModuleScore) %>%
    select(-ix)


shuffled_df <- pseudobulk_scores_df %>%
    filter(ix != "cat_dist") %>%
    mutate(AddModuleScore = as.numeric(AddModuleScore)) %>%
    rename(AddModuleScore_shuffled = AddModuleScore)

stat_df <- shuffled_df %>%
    left_join(obs_df)

stat_df_wide <- stat_df %>%
    pivot_wider(names_from = ix, values_from = AddModuleScore_shuffled) %>%
    rowwise() %>%
    mutate(
        perm_min = min(c_across(starts_with("cat_dist_sid"))),
        perm_max = max(c_across(starts_with("cat_dist_sid"))),
        perm_mean = mean(c_across(starts_with("cat_dist_sid"))),
        perm_median = median(c_across(starts_with("cat_dist_sid"))),
        perm_sd = sd(c_across(starts_with("cat_dist_sid"))),
        # Testing hypothesis H0 < H1 (alternative = 'greater')
        count_larger = sum(c_across(starts_with("cat_dist_sid_")) > AddModuleScore_obs) + 1,
        # Testing hypothesis H0 > H1 (alternative = 'less')
        count_smaller = sum(c_across(starts_with("cat_dist_sid_")) < AddModuleScore_obs) + 1,
        z_score = (AddModuleScore_obs - perm_mean) / perm_sd,
        interaction_type = ifelse(
            z_score > 0,
            "Co-localization",
            "Avoidance"
        ),
        p_value = ifelse(interaction_type == "Co-localization",
            # Co-localization
            count_larger / params$n_iter,
            count_smaller / params$n_iter
        ),
        p_value_coloc = count_larger / params$n_iter,
        p_value_avoid = count_smaller / params$n_iter,
    ) %>%
    mutate(cat_dist = ifelse(cat_dist == paste0(
        params$lower_limit * 100, "% <= mean distance <= ",
        params$upper_limit * 100, "%"
    ), "between", cat_dist)) %>%
    filter(cat_dist != "between")


stat_df_wide$p_value_adj <- p.adjust(stat_df_wide$p_value, "bonferroni")

stat_res_df <- stat_df_wide %>%
    mutate(
        is_significant = p_value < 0.05,
        is_significant_adj = p_value_adj < 0.05,
        variable = factor(str_replace_all(variable, "_", "-"), c("Differentiated-like", "Progenitor-like", "Invasive-high OPC/NPC1"))
    ) %>%
    mutate(
        cat_dist_renamed = factor(ifelse(cat_dist == paste0("<", params$lower_limit * 100, "%"), "Closer to\nNeurons", "Closer to\ntumor core"), levels = c("Closer to\nNeurons", "Closer to\ntumor core"))
    )
color_labels <- GBMutils::load_color_palette("Divergent_1")
```

### Option 1: histogram
```{r}
color_gradient <- setNames(RColorBrewer::brewer.pal(n = 8, name = "Blues")[c(3, 8)], c("Closer to\nNeurons", "Closer to\ntumor core"))


stat_res_shuffled_df_long <- stat_res_df %>%
    select(cat_dist_renamed, variable, starts_with("cat_dist_sid")) %>%
    rename(signature = variable) %>%
    reshape2::melt()

stat_res_obs_df <- stat_res_df %>%
    select(cat_dist_renamed, variable, AddModuleScore_obs, perm_median, z_score, p_value, p_value_adj) %>%
    distinct()

p <- ggplot(data = stat_res_shuffled_df_long %>% filter(signature == "Invasive-high OPC/NPC1"), aes(x = value, fill = cat_dist_renamed)) +
    geom_histogram(binwidth = 1e-3, show.legend = FALSE) +
    ggh4x::facet_wrap2(. ~ cat_dist_renamed, ncol = 1, axes = "all", scales = "free_x") +
    geom_vline(data = stat_res_obs_df %>% filter(variable == "Invasive-high OPC/NPC1"), aes(xintercept = AddModuleScore_obs, color = cat_dist_renamed)) +
    geom_vline(data = stat_res_obs_df %>% filter(variable == "Invasive-high OPC/NPC1"), aes(xintercept = perm_median), color = "red", linetype = "dashed") +
    scale_x_continuous(breaks = scales::pretty_breaks()) +
    scale_y_continuous(breaks = scales::pretty_breaks()) +
    GBMutils::GBM_theme() +
    scale_fill_manual(values = color_gradient, guide = guide_legend(override.aes = list(size = 5))) +
    scale_color_manual(values = color_gradient, guide = guide_legend(title = "Observed score", override.aes = list(size = 5))) +
    labs(
        x = "Module Score", y = "No. of iterations", subtitle =
            glue("k={params$k_neighbors} with no. iterations={prettyNum(params$n_iter, big.mark =',')}"),
    ) +
    theme(aspect.ratio = 0.5)
ggsave(p, filename = glue("Fig2f-malign_signature_vs_proximity_k{params$k_neighbors}_histo.pdf"), width = 6, path = params$output_dir)
```

```{r}
color_gradient <- setNames(RColorBrewer::brewer.pal(n = 8, name = "Blues")[c(3, 8)], c("Closer to\nNeurons", "Closer to\ntumor core"))


stat_res_shuffled_df_long <- stat_res_df %>%
    select(cat_dist_renamed, variable, starts_with("cat_dist_sid")) %>%
    rename(signature = variable) %>%
    reshape2::melt()

stat_res_obs_df <- stat_res_df %>%
    select(cat_dist_renamed, variable, AddModuleScore_obs, perm_median, z_score, p_value, p_value_adj) %>%
    distinct()

p <- ggplot(data = stat_res_shuffled_df_long %>% filter(signature != "Invasive-high OPC/NPC1"), aes(x = value, fill = cat_dist_renamed)) +
    geom_histogram(binwidth = 1e-3, show.legend = FALSE) +
    ggh4x::facet_grid2(signature ~ cat_dist_renamed, axes = "all", scales = "free_x") +
    geom_vline(data = stat_res_obs_df %>% filter(variable != "Invasive-high OPC/NPC1"), aes(xintercept = AddModuleScore_obs, color = cat_dist_renamed)) +
    geom_vline(data = stat_res_obs_df %>% filter(variable != "Invasive-high OPC/NPC1"), aes(xintercept = perm_median), color = "red", linetype = "dashed") +
    scale_x_continuous(breaks = scales::pretty_breaks()) +
    scale_y_continuous(breaks = scales::pretty_breaks()) +
    GBMutils::GBM_theme() +
    scale_fill_manual(values = color_gradient, guide = guide_legend(override.aes = list(size = 5))) +
    scale_color_manual(values = color_gradient, guide = guide_legend(title = "Observed score", override.aes = list(size = 5))) +
    labs(
        x = "Module Score", y = "No. of iterations", subtitle =
            glue("k={params$k_neighbors} with no. iterations={prettyNum(params$n_iter, big.mark =',')}"),
    ) +
    theme(aspect.ratio = 0.5)
ggsave(p, filename = glue("SuppFig5-malign_signature_vs_proximity_k{params$k_neighbors}_histo_PL_and_DL.pdf"), width = 12, path = params$output_dir)
```

### Option 2: Barplot
```{r}
palette <- GBMutils::load_color_palette("Spatial_CellClass_L2")
palette <- setNames(palette, str_replace_all(names(palette), "_", "-"))
# Option 2
stat_res_df <- stat_df_wide %>%
    select(variable, cat_dist, z_score, interaction_type, p_value, p_value_adj) %>%
    mutate(cat_dist = ifelse(cat_dist == paste0(
        params$lower_limit * 100, "% <= mean distance <= ",
        params$upper_limit * 100, "%"
    ), "between", cat_dist)) %>%
    mutate(
        is_significant = p_value < 0.05,
        is_significant_adj = p_value_adj < 0.05,
        variable = factor(str_replace_all(variable, "_", "-"), c("Differentiated-like", "Progenitor-like", "Invasive-high OPC/NPC1"))
    ) %>%
    filter(cat_dist != "between") %>%
    mutate(
        cat_dist_renamed = factor(ifelse(cat_dist == paste0("<", params$lower_limit * 100, "%"), "Closer to\nNeurons", "Closer to\ntumor core"), levels = c("Closer to\nNeurons", "Closer to\ntumor core"))
    )

p <- ggplot(data = stat_res_df, aes(
    fill = variable,
    x = variable, y = z_score
)) +
    ggh4x::facet_wrap2(. ~ cat_dist_renamed, axes = "all", ncol = 1) +
    geom_bar(stat = "identity", position = "dodge", show.legend = FALSE) +
    scale_fill_manual(values = palette) +
    scale_y_continuous(breaks = scales::pretty_breaks()) +
    GBMutils::GBM_theme() +
    labs(
        subtitle =
            glue("k={params$k_neighbors} with no. iterations={prettyNum(params$n_iter, big.mark =',')}"),
        y = "Z-score", x = "Signature"
    ) +
    coord_flip() +
    theme(strip.text.x.top = element_text(size = rel(0.95)))
ggsave(p, filename = glue("Fig2f-malign_signature_vs_proximity_k{params$k_neighbors}_barplot.pdf"), height = 8, path = params$output_dir)
```

### Option 3: old version
```{r}
stat_res_df <- stat_df_wide %>%
    select(variable, cat_dist, z_score, interaction_type, p_value, p_value_adj) %>%
    mutate(cat_dist = ifelse(cat_dist == paste0(
        params$lower_limit * 100, "% <= mean distance <= ",
        params$upper_limit * 100, "%"
    ), "between", cat_dist)) %>%
    mutate(
        is_significant = p_value < 0.05,
        is_significant_adj = p_value_adj < 0.05,
        variable = factor(str_replace_all(variable, "_", "-"), c("Differentiated-like", "Progenitor-like", "Invasive-high OPC/NPC1"))
    ) %>%
    filter(cat_dist != "between") %>%
    mutate(
        cat_dist_renamed = factor(ifelse(cat_dist == paste0("<", params$lower_limit * 100, "%"), "Closer to\nNeurons", "Closer to\ntumor core"), levels = c("Closer to\nNeurons", "Closer to\ntumor core"))
    )
color_labels <- GBMutils::load_color_palette("Divergent_1")


p <- ggplot(data = stat_res_df %>% arrange(variable), aes(x = variable, y = cat_dist_renamed, fill = z_score, size = -log10(p_value_adj))) +
    geom_point(pch = 21, color = "black", show.legend = TRUE, size = 10) +
    geom_point(data = stat_res_df %>% filter(!is_significant_adj), shape = 4, show.legend = FALSE, size = 10) +
    GBMutils::GBM_theme() +
    scale_fill_gradient2(
        mid = color_labels[["mid"]], midpoint = 0, low = color_labels[["low"]], high = color_labels[["high"]],
        breaks = scales::pretty_breaks(),
        n.breaks = 3
    ) +
    labs(
        subtitle =
            glue("k={params$k_neighbors} with no. iterations={prettyNum(params$n_iter, big.mark =',')}"),
        x = "Signature", y = "Bin label"
    ) +
    scale_y_discrete(
        limits = c("Closer to\nNeurons", "Closer to\ntumor core")
    ) +
    guides(
        fill = guide_colorbar(
            title.position = "top",
            title.hjust = 0.5,
            title = "z-score",
            barwidth = unit(10, "lines"),
            barheight = unit(0.9, "lines"),
        )
    ) +
    theme(
        legend.key.width = unit(2, "lines"),
        legend.box = "horizontal", aspect.ratio = 1.5
    ) +
    coord_flip()
print(p)
ggsave(plot = p, path = params$output_dir, filename = glue("Fig2f-malign_signature_vs_proximity_k{params$k_neighbors}_binary.pdf"))

log_info("Finished!")
```

## Session Info
```{r, session-info, echo = FALSE}
sessionInfo()
```
