---
title: "Notebook to reproduce Figure 2c"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
author: "Joan Kant"
params:
    output_dir: "output/CCI_CellClass_L2_2_rerun"
    interactions:  "data/cci/402b_aggregation_samples.rds"
    condition_varname: "Region"
    condition_oi: "PT"
    pair_y: "Neuron__Invasive-high OPC/NPC1"
    pair_x: "Neuron__Progenitor_like"
    pval_type: "pval_adj"
    alpha: 0.05
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
options(ggrepel.max.overlaps = Inf)

pacman::p_load(GaitiLabUtils, GBMutils, glue, data.table, tidyverse, stringr, readxl, ggplot2, ggrastr, ggtext, ggpubr, ggrepel)

# params <- list()
# params$output_dir <- "/Users/joankant/Desktop/gaitigroup/Users/Joan/gbm_manuscript/output/CCI_CellClass_L2_2_rerun"
# params$interactions <-  "/Users/joankant/Desktop/gaitigroup/Users/Joan/GBM_CCI_Analysis/output/CCI_CellClass_L2_2_rerun/402_aggregation_and_filtering/402b_aggregation_samples.rds"
# params$condition_varname <- "Region"
# params$condition_oi <- "PT"
# params$pair_y <- "Neuron__Invasive-high OPC/NPC1"
# params$pair_x <- "Neuron__Progenitor_like"
# params$pval_type <- "pval_adj"
# params$alpha <- 0.05

create_dir(params$output_dir)

outfile <- str_replace_all(paste0(params$pair_x, "_vs_", params$pair_y), c("\\/" = "_", " " = "_"))

# Setup color palettes
color_labels <- GBMutils::load_color_palette("Divergent_1")
```

## Prepare & format data
```{r}
# Load aggregated CCI object
interactions <- readRDS(params$interactions)

# Filter for cell type pairs and condition of interest
interactions_filtered <- interactions %>%
    filter(
        # Only keep interactions detected for Neuron - Progenitor-like OR Neuron - Invasive-high OPC/NPC1
        source_target %in% c(params$pair_x, params$pair_y),
        # Keep interactions that are detected in PT region
        !!sym(params$condition_varname) == params$condition_oi,
    ) %>%
    ungroup() %>%
    select(complex_interaction, source_target, !!sym(params$pval_type)) %>%
    data.frame()

# Extract list of interactions
interactions_signif <- interactions_filtered %>%
    # Only keep interactions with a (adjusted) Fisher combined p-value < 0.05
    filter(!!sym(params$pval_type) < params$alpha) %>%
    pull(complex_interaction) %>%
    unique()

interactions_filtered_wider <- interactions_filtered %>%
    filter(complex_interaction %in% interactions_signif) %>%
    mutate(log10p = -log10(!!sym(params$pval_type))) %>%
    ungroup() %>%
    # Remove original p-val
    select(-!!sym(params$pval_type)) %>%
    # Remove duplicates
    distinct() %>%
    # Convert to wider format
    pivot_wider(
        names_from = source_target,
        values_from = log10p,
        values_fill = NA
    ) %>%
    separate(complex_interaction, into = c("ligand_complex", "receptor_complex"), sep = "__", remove = FALSE) %>%
    # Convert -log10(pval) to ranks (integers)
    mutate(
        pair_x = dense_rank(desc(!!sym(params$pair_x))),
        pair_y = dense_rank(desc(!!sym(params$pair_y))),
        # Compute residuals based on y = x
        resid = pair_x - pair_y,
        # Label residuals based on whether they are above (high) or below (low) the y = x line
        is_pos = case_when(
            # Positive (more biased towards invasive)
            sign(resid) == 1 ~ "high",
            # Negative (more biased towards PL-like)
            sign(resid) == -1 ~ "low",
        ),
        # Label interactions of interest (1) NRXN-NLGN / NRXN-NLGN interactions OR glutamate related
        interaction_oi =
        # NRXN-NLGN / NRXN-NLGN interactions
            ((str_detect(ligand_complex, "NRXN") & str_detect(receptor_complex, "NLGN")) |
                (str_detect(ligand_complex, "NLGN") & str_detect(receptor_complex, "NRXN"))),
        label_interaction =
            case_when(
                # Positive
                is_pos == "high" &
                    interaction_oi ~ "high",
                # Negative
                is_pos == "low" & interaction_oi ~ "low",
                .default = "background"
            )
    ) %>%
    # Only keep rows (interactions) that are in the top-50% for both pairs.
    filter(pair_x < median(pair_x), pair_y < median(pair_y))

all_vals <- interactions_filtered_wider %>%
    select(pair_x, pair_y) %>%
    unlist() %>%
    c()

max_ax_val <- plyr::round_any(max(all_vals), 50, f = ceiling)
```
## Visualization
```{r,  fig.width = 15, fig.height = 15}
# Color by interest + transparency
p <- ggplot(
    # TODO only keep interactions of interest for plotting
    data = interactions_filtered_wider,
    aes(
        x = pair_x,
        y = pair_y,
    )
) +
    geom_point(aes(color = resid),
        show.legend = TRUE
    ) +
    scale_color_gradient2(
        breaks = c(-max_ax_val, 0, max_ax_val),
        midpoint = 0,
        limits = c(-max_ax_val, max_ax_val),
        low = unname(color_labels["low"]),
        high = unname(color_labels["high"]),
        guide = guide_colorbar(
            title = "Residuals",
            title.position = "top",
            barwidth = unit(10, "lines"),
            barheight = unit(0.9, "lines"),
        )
    ) +
    GBM_theme() +
    coord_equal() +
    labs(
        x = paste0("rank in ", str_replace_all(params$pair_x, c("__" = " - ", "_" = "-"))),
        y = paste0("rank in ", str_replace_all(params$pair_y, c("__" = " - ", "_" = "-"))),
        subtitle = glue("N={nrow(interactions_filtered_wider)}")
    ) +
    ggnewscale::new_scale_color() +
    geom_abline(slope = 1, linetype = "dashed") +
    # Label interactions of interest
    geom_label_repel(
        data = interactions_filtered_wider %>%
            filter(
                label_interaction != "background"
            ),
        aes(
            label = str_replace_all(complex_interaction, "__", " - "),
            color = is_pos
        ),
        min.segment.length = unit(0.1, "lines"), show.legend = FALSE
    ) +
    scale_color_manual(values = color_labels, guide = "none") +
    scale_x_reverse(n.breaks = 4, limits = rev(c(0, max_ax_val)), expand = c(0, 0)) +
    scale_y_reverse(n.breaks = 4, limits = rev(c(0, max_ax_val)), expand = c(0, 0)) +
    theme(legend.title = element_text(hjust = 0.5))

p
# Save plot
ggsave(plot = p, filename = glue("{params$output_dir}/{outfile}_interactions_oi.pdf"), width = 12, height = 12)
```

## Session Info
```{r echo = false}
sessionInfo()
```