---
title: "Notebook to reproduce Figure 3b"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
author: "Yiyan Wu"
params:
  integrated_object: "data/gbm_regional_study.rds"
  integrated_atac_only_object: "data/integrated_atac_only_object.rds"
  output_dir: "output"
output: html_document
---

```{r, rmarkdown-setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here(), warning = FALSE)
```

## Prepare data
```{r, prep-data}
pacman::p_load(GaitiLabUtils, GBMutils, glue, data.table, tidyverse, stringr, Seurat, Signac, stringr, BSgenome.Hsapiens.UCSC.hg38, EnsDb.Hsapiens.v86, dplyr, Rsamtools, stringi, fastmatch, RcppRoll, scales, patchwork, tidyr, Matrix, GenomicRanges)

# Plot genome browser tracks with Seurat
integrated_seurat <- readRDS(params$integrated_object)
metadata <- integrated_seurat[[]] %>%
  dplyr::filter(Platform == "Multiome") %>%
  dplyr::filter(CellClass_L1 == "Malignant") %>%
  dplyr::filter(Confident_Annotation == "TRUE") %>%
  dplyr::select(CellID, CellClass_L5_2)

# Load seurat object for visualization
curr_seurat_data <- readRDS(params$integrated_atac_only_object)
curr_seurat_data <- subset(curr_seurat_data, subset = CellClass_L1 == "Malignant")

# Add metadata
curr_seurat_data <- subset(curr_seurat_data, subset = CellID %in% metadata$CellID) # Filter cells
metadata <- metadata[match(curr_seurat_data$CellID, metadata$CellID), ] # Match metadata rows
metadata <- metadata %>%
  mutate(CellClass_L5_2 = case_when(
    CellClass_L5_2 == "Malignant_NPC1" ~ "NPC1-like",
    CellClass_L5_2 == "Malignant_NPC2" ~ "NPC2-like",
    CellClass_L5_2 == "Malignant_OPC" ~ "OPC-like",
    CellClass_L5_2 == "Malignant_AC" ~ "AC-like",
    CellClass_L5_2 == "Malignant_MES_AST" ~ "MES-AC-like",
    CellClass_L5_2 == "Malignant_MES_INT" ~ "MES-INT-like",
    CellClass_L5_2 == "Malignant_MES_HYP" ~ "MES-HYP-like",
    CellClass_L5_2 == "Invasive-high OPC/NPC1" ~ "Invasive-high OPC/NPC1-like"
  ))
curr_seurat_data <- AddMetaData(curr_seurat_data, metadata$CellClass_L5_2, col.name = "CellClass_L5_2")

# Define custom color palette
color_palette <- c(
  "NPC1-like" = "#86CCE8",
  "NPC2-like" = "#ADD7E5",
  "OPC-like" = "#AECFA5",
  "AC-like" = "#DFB63B",
  "MES-AC-like" = "#F37F72",
  "MES-INT-like" = "#B02425",
  "MES-HYP-like" = "#F1634B",
  "Invasive-high OPC/NPC1-like" = "#2B7095"
)

# Set ident
Idents(curr_seurat_data) <- "CellClass_L5_2"
DefaultAssay(curr_seurat_data) <- "ATAC"

curr_seurat_data$CellClass_L5_2 <- factor(curr_seurat_data$CellClass_L5_2, levels = c("Invasive-high OPC/NPC1-like", "NPC1-like", "NPC2-like", "OPC-like", "AC-like", "MES-AC-like", "MES-INT-like", "MES-HYP-like"))
```

```{r, vis-annot, fig.width = 10, fig.height = 10 }
# GenePlot
gene_plot <- AnnotationPlot(
  object = curr_seurat_data,
  region = c("chr19-39497000-39509000")
)
ggsave(
  filename = paste0(params$output_dir, "/AnnotationPlot_DLL3.pdf"),
  plot = gene_plot,
  width = 10,
  height = 10
)
gene_plot
```


```{r, vis-exp, fig.width = 10, fig.height = 10}
# expression
expr_plot <- ExpressionPlot(
  object = curr_seurat_data,
  features = "DLL3",
  group.by = "CellClass_L5_2",
  assay = "RNA",
  slot = "data"
) +
  scale_fill_manual(values = color_palette)
ggsave(
  filename = paste0(params$output_dir, "/ExpressionPlot_DLL3.pdf"),
  plot = expr_plot,
  width = 10,
  height = 10
)
expr_plot
```

```{r, vis-cov, fig.width= 10, fig.height = 10}
source("utils/utilities.R")
source("utils/visualization.R")
source("utils/fragments.R")

# CoveragePlot
cov_plot <- CoveragePlot(
  object = curr_seurat_data,
  region = "chr19-39497000-39509000",
  group.by = "CellClass_L5_2",
  annotation = FALSE,
  peaks = FALSE
) +
  scale_fill_manual(values = color_palette)
ggsave(
  filename = paste0(params$output_dir, "/CoveragePlot_DLL3.pdf"),
  plot = cov_plot,
  width = 10,
  height = 10
)
cov_plot
```

```{r, vis-combined, fig.width = 10, fig.height = 10}
combined <- CombineTracks(
  plotlist = list(cov_plot, gene_plot),
  expression.plot = expr_plot,
  heights = c(8, 1),
  widths = c(5, 1)
)
ggsave(
  filename = paste0(params$output_dir, "/Combined_DLL3.pdf"),
  plot = combined,
  width = 7,
  height = 5
)
combined
```

## Session Info
```{r, session-info, echo = FALSE}
sessionInfo()
```
