---
title: "Notebook to reproduce Figure 3c"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
author: "Yiyan Wu"
params:
    output_dir: "output"
    region_auc_activator_mtx: "data/region_auc_activator_mtx.csv"
    TFs_to_label: "data/TFs_to_label.csv"
output: html_document
---


```{r, rmarkdown-setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here(), warning = FALSE)
```

## Prepare data
```{r, prep-data}
pacman::p_load(ComplexHeatmap, data.table, dplyr, circlize, viridis)

# Load your data
matrix_data <- fread(params$region_auc_activator_mtx)
labels_data <- fread(params$TFs_to_label)

# Convert matrix data to data frame and set row names
matrix_data <- as.data.frame(matrix_data)
row.names(matrix_data) <- matrix_data$V1 # Assuming the first column contains the row names (e.g., gene names)
matrix_data <- matrix_data[, -1] # Remove the first column after setting it as row names

# Convert labels data to data frame
labels_data <- as.data.frame(labels_data)
labels_data <- labels_data[-1, ] # Remove the first row if it contains column names
row.names(labels_data) <- labels_data$V1
labels_data <- labels_data[, -1]

# Scale the matrix data (Z-score normalization across rows)
scaled_matrix <- t(apply(matrix_data, 1, scale))
colnames(scaled_matrix) <- colnames(matrix_data)

# Create a vector of labels and their positions
label_positions <- which(row.names(scaled_matrix) %in% labels_data)
label_names <- labels_data
```

## Visualization
```{r, vis-hm, fig.width = 4, fig.height = 8}
# Define the heatmap annotation with lines pointing to the labels using anno_link
ha <- rowAnnotation(mark = anno_mark(
    at = label_positions, # Positions of the labels
    labels = label_names, # Label names
    side = "right", # Place the labels on the right
    labels_gp = gpar(fontsize = 8), # Adjust font size of labels
    link_gp = gpar(col = "black") # Customize line appearance
))

# Save the heatmap to a PDF
pdf(file = paste0(params$output_dir, "/heatmap_with_labels.pdf"), width = 4, height = 8)

# Create the heatmap
Heatmap(scaled_matrix,
    name = "Scaled Data",
    row_names_gp = gpar(fontsize = 8), # Adjust font size for row names
    column_names_gp = gpar(fontsize = 8), # Adjust font size for column names
    right_annotation = ha, # Add the row annotation with lines pointing to labels
    show_row_names = FALSE, # Hide original row names since we are adding custom labels with lines
    col = rocket(n = 256, direction = -1, begin = 0.2, end = 0.8)
) # Use rocket_r color scale

# Close the PDF device
dev.off()
```

## Session Info
```{r, session-info, echo = FALSE}
sessionInfo()
```
