---
title: "Notebook to reproduce Figure S5XX"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
author: "Joan Kant"
params:
    log_level: 5
    output_dir: "output/cci_scRNAseq"
    interactions: "preprocessing/scRNAseq/CCI_CellClass_L2_2/output/402_aggregation_and_filtering/402c_filtering_aggregated_res.rds"
    condition_varname: "Region"
    group1: "PT"
    group2: "TC"
    remove_autocrine: TRUE
    pval_type: "pval_adj"
    alpha: 0.05
output: 
    html_document:
        toc: true

---



```{r, rmarkdown-setup, include=FALSE}
knitr::opts_knit$set(
    root.dir = here::here()
)
knitr::opts_chunk$set(
    fig.align = "center", fig.width = 12, warning = FALSE
)

# ---- Parameters (only interactive) ----
params <- list()
params$log_level <- 5
params$output_dir <- "output/cci_scRNAseq_secondSubmission"
params$interactions <- "preprocessing/scRNAseq/CCI_CellClass_L2_2/output/402_aggregation_and_filtering/402c_filtering_aggregated_res.rds"
params$condition_varname <- "Region"
params$group1 <- "PT"
params$group2 <- "TC"
params$remove_autocrine <- TRUE
params$pval_type <- "pval_adj"
params$alpha <- 0.05
```

```{r, config}
pacman::p_load(GaitiLabUtils, GBMutils, glue, data.table, tidyverse, stringr, ComplexHeatmap)

# Setup color palettes
color_group1 <- GBMutils::load_color_palette("Region")[[params$group1]]
color_group2 <- GBMutils::load_color_palette("Region")[[params$group2]]

# Setup celltype categories/labels
celltype_levels <- names(GBMutils::load_color_palette("CCI_CellClass_L2_2"))
malign <- celltype_levels[1:3]
tme_oi <- c("Myeloid_Inflammatory", "Myeloid_Immunosuppressive", "GABAergic", "Glutamatergic", "Neuron")
tme_other <- setdiff(celltype_levels, c(malign, tme_oi))
celltype_levels <- c(malign, tme_oi, tme_other)
label_levels <- c("Tumor", "TME\nof interest", "TME")

malignant_signatures <- rev(c("Differentiated-like", "Progenitor-like", "Invasive-high OPC/NPC1"))


GaitiLabUtils::create_dir(params$output_dir)
```

## Prepare & format data
```{r, prep-and-format-data}
# Load data + formatting
obj <- readRDS(params$interactions) %>%
    # Only keep significant interactions based on (ajusted) Fisher' combined p-value
    filter(!!sym(params$pval_type) < params$alpha) %>%
    separate(source_target, c("source", "target"), sep = "__", remove = FALSE) %>%
    # Remove direction by sorting source-target alphabetically
    rowwise() %>%
    mutate(source_target_undirected = paste0(sort(c(source, target)), collapse = "__")) %>%
    # Remove duplicate interactions, when they are found in both directions only keep 1
    distinct(!!sym(params$condition_varname), source_target_undirected, complex_interaction, .keep_all = FALSE) %>%
    separate(source_target_undirected, c("source", "target"), sep = "__") %>%
    arrange(!!sym(params$condition_varname), source, target, .by_group = TRUE) %>%
    # Count number of interactions per source-target per region
    group_by(!!sym(params$condition_varname), target, source) %>%
    summarise(n = n()) %>%
    ungroup()

obj %>%
    filter(target %in% c("GABAergic", "Glutamatergic"))

obj %>%
    filter(source %in% c("GABAergic", "Glutamatergic"))


# Convert to wide format based on levels in '{params$condition_varname}'
obj_wide_condition <- obj %>%
    # Replace missing values with 0
    pivot_wider(names_from = !!sym(params$condition_varname), values_from = n, values_fill = 0) %>%
    select(source, target, !!sym(params$group1), !!sym(params$group2)) %>%
    mutate(diff_n = !!sym(params$group1) - !!sym(params$group2))

obj_PT <- obj_wide_condition %>%
    select(source, target, PT) %>%
    arrange(target) %>%
    pivot_wider(names_from = target, values_from = PT, values_fill = 0) %>%
    column_to_rownames("source")

# Convert to matrix
mat <- data.matrix(obj_PT)
colnames(mat) <- str_replace_all(colnames(mat), "_", "-")
rownames(mat) <- str_replace_all(rownames(mat), "_", "-")


# Make sure order of rows/columns are the same.
mat <- mat[
    intersect(str_replace_all(celltype_levels, "_", "-"), rownames(mat)),
    intersect(str_replace_all(celltype_levels, "_", "-"), colnames(mat))
]

# Fill whole matrix (mirror)
mat <- mat + t(mat)
mat[lower.tri(mat)] <- 0

if (params$remove_autocrine) {
    # Remove autocrine interactions (diagonal)
    diag(mat) <- 0
}

# Remove fully empty columns/rows
mat <- mat[, which(colSums(mat) != 0)]
mat <- mat[which(rowSums(mat) != 0), ]

ninteractions_df <- data.frame(mat, check.names = FALSE)
```

```{r, gluta-vs-malign}
glutamatergic_vs_malign_df <- ninteractions_df[str_replace_all(malign, "_", "-"), ]["Glutamatergic"] %>%
    rownames_to_column("Malignant_subtype") %>%
    mutate(Malignant_subtype = factor(Malignant_subtype, levels = malignant_signatures))

p_bar <- ggplot(data = glutamatergic_vs_malign_df, aes(x = Malignant_subtype, y = Glutamatergic)) +
    geom_bar(stat = "identity", fill = "grey", color = "black") +
    GBMutils::GBM_theme() +
    labs(
        x = "Malignant subtype",
        y = "No. interactions",
        title = "Interactions between Glutamatergic Neurons and Malignant cells"
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) +
    coord_flip() +
    theme(plot.title = ggtext::element_markdown(size = rel(0.65)))
ggsave(p_bar, filename = glue("FigS5XX-glutamatergic_vs_malign_n_interactions_bar.pdf"), height = 3, path = params$output_dir, )
```

```{r, gluta-vs-gaba-invasive}
gaba_vs_gluta_df <- data.frame(ninteractions_df["Invasive-high OPC/NPC1", ][c("GABAergic", "Glutamatergic")]) %>% reshape2::melt(variable.name = "neuron_subtype", value.name = "n")

p_bar <- ggplot(data = gaba_vs_gluta_df, aes(x = neuron_subtype, y = n), ) +
    geom_bar(stat = "identity", fill = "grey", color = "black") +
    GBMutils::GBM_theme() +
    labs(
        x = "Neuron subtype",
        y = "No. interactions",
        title = "No. interactions between Neurons and Invasive-high OPC/NPC1"
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks()) +
    coord_flip() +
    theme(plot.title = ggtext::element_markdown(size = rel(0.55)))

ggsave(p_bar, filename = glue("FigS5XX-glutamatergic_vs_gabaergic_invasivehigh_interactions_bar.pdf"), height = 2.5, width = 5, path = params$output_dir)
```

# Session Info
```{r, session-info, echo = FALSE}
sessionInfo()
```
